import { Inter } from 'next/font/google'
import './home.css'
import NavBar from './components/share_component/navbar/NavBar'
import Footer from './components/share_component/footer/Footer'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Accessorices Shop',
  description: 'Generated by accessorices shop',

}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
