import { Inter } from 'next/font/google'
import './home.css'
const inter = Inter({ subsets: ['latin'] })
import NavBar from '@/src/components/share_component/navbar/NavBar'
import Footer from '@/src/components/share_component/footer/Footer'
import Provider from '@/src/utils/queryProvider/queryProvider'



export const metadata = {
  title: 'Accessorices Shop',
  description: 'Generated by accessorices shop',

}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>

        <Provider>
          <NavBar />
          {children}
        </Provider>
        <Footer />
      </body>
    </html>
  )
}
